using System.Drawing;
using System.Windows.Forms;

namespace SIMS_WinFormsApp.Views.Catalog
{
    partial class frmProductEditor
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel _root;
        private Label _titleLabel;
        private Panel _codePanel;
        private Label _codeLabel;
        private TableLayoutPanel _body;
        private TableLayoutPanel _fields;
        private GroupBox _detailsGroup;
        private Label _nameLabel;
        private TextBox _nameTextBox;
        private Label _categoryLabel;
        private ComboBox _categoryComboBox;
        private Label _supplierLabel;
        private ComboBox _supplierComboBox;
        private Label _brandLabel;
        private TextBox _brandTextBox;
        private Label _unitLabel;
        private TextBox _unitTextBox;
        private Label _weightLabel;
        private TextBox _weightTextBox;
        private Label _descriptionLabel;
        private TextBox _descriptionTextBox;
        private Label _importPriceLabel;
        private TextBox _importPriceTextBox;
        private Label _sellPriceLabel;
        private TextBox _sellPriceTextBox;
        private Label _stockLabel;
        private TextBox _stockTextBox;
        private Label _minStockLabel;
        private TextBox _minStockTextBox;
        private Label _statusLabel;
        private ComboBox _statusComboBox;
        private GroupBox _imageGroup;
        private PictureBox _preview;
        private Button _uploadImageButton;
        private Button _clearImageButton;
        private Label _detailSummaryLabel;
        private FlowLayoutPanel _footer;
        private Button _saveButton;
        private Button _closeButton;

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            _root = new TableLayoutPanel();
            _titleLabel = new Label();
            _codePanel = new Panel();
            _codeLabel = new Label();
            _body = new TableLayoutPanel();
            _fields = new TableLayoutPanel();
            _detailsGroup = new GroupBox();
            _nameLabel = new Label();
            _nameTextBox = new TextBox();
            _categoryLabel = new Label();
            _categoryComboBox = new ComboBox();
            _supplierLabel = new Label();
            _supplierComboBox = new ComboBox();
            _brandLabel = new Label();
            _brandTextBox = new TextBox();
            _unitLabel = new Label();
            _unitTextBox = new TextBox();
            _weightLabel = new Label();
            _weightTextBox = new TextBox();
            _descriptionLabel = new Label();
            _descriptionTextBox = new TextBox();
            _importPriceLabel = new Label();
            _importPriceTextBox = new TextBox();
            _sellPriceLabel = new Label();
            _sellPriceTextBox = new TextBox();
            _stockLabel = new Label();
            _stockTextBox = new TextBox();
            _minStockLabel = new Label();
            _minStockTextBox = new TextBox();
            _statusLabel = new Label();
            _statusComboBox = new ComboBox();
            _imageGroup = new GroupBox();
            _preview = new PictureBox();
            _uploadImageButton = new Button();
            _clearImageButton = new Button();
            _detailSummaryLabel = new Label();
            _footer = new FlowLayoutPanel();
            _saveButton = new Button();
            _closeButton = new Button();
            _root.SuspendLayout();
            _codePanel.SuspendLayout();
            _body.SuspendLayout();
            _detailsGroup.SuspendLayout();
            _fields.SuspendLayout();
            _imageGroup.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_preview).BeginInit();
            _footer.SuspendLayout();
            SuspendLayout();

            _root.ColumnCount = 1;
            _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _root.Dock = DockStyle.Fill;
            _root.Padding = new Padding(24, 18, 24, 18);
            _root.RowCount = 5;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 74F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            _root.Controls.Add(_titleLabel, 0, 0);
            _root.Controls.Add(_codePanel, 0, 1);
            _root.Controls.Add(_body, 0, 2);
            _root.Controls.Add(_detailSummaryLabel, 0, 3);
            _root.Controls.Add(_footer, 0, 4);

            _titleLabel.Dock = DockStyle.Fill;
            _titleLabel.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
            _titleLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _titleLabel.Text = "Thông tin sản phẩm";
            _titleLabel.TextAlign = ContentAlignment.MiddleLeft;
            _codePanel.BackColor = Color.FromArgb(241, 245, 249);
            _codePanel.Controls.Add(_codeLabel);
            _codePanel.Dock = DockStyle.Fill;
            _codeLabel.AutoSize = true;
            _codeLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _codeLabel.Location = new Point(10, 8);
            _codeLabel.Name = "_codeLabel";
            _codeLabel.Text = "Mã sản phẩm";

            _body.ColumnCount = 2;
            _body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 72F));
            _body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 28F));
            _body.Dock = DockStyle.Fill;
            _body.Controls.Add(_detailsGroup, 0, 0);
            _body.Controls.Add(_imageGroup, 1, 0);
            _detailsGroup.Dock = DockStyle.Fill;
            _detailsGroup.Margin = new Padding(0, 6, 10, 6);
            _detailsGroup.Padding = new Padding(12);
            _detailsGroup.Text = "Thông tin sản phẩm";
            _detailsGroup.Controls.Add(_fields);

            _fields.ColumnCount = 4;
            _fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _fields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _fields.Dock = DockStyle.Fill;
            _fields.RowCount = 14;
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            _fields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _nameLabel.AutoSize = true;
            _nameLabel.Dock = DockStyle.Fill;
            _nameLabel.Text = "Tên sản phẩm";
            _nameLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_nameLabel, 0, 0);
            _fields.SetColumnSpan(_nameLabel, 4);
            _nameTextBox.Dock = DockStyle.Fill;
            _nameTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_nameTextBox, 0, 1);
            _fields.SetColumnSpan(_nameTextBox, 4);
            _categoryLabel.AutoSize = true;
            _categoryLabel.Dock = DockStyle.Fill;
            _categoryLabel.Text = "Danh mục";
            _categoryLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_categoryLabel, 0, 2);
            _fields.SetColumnSpan(_categoryLabel, 2);
            _categoryComboBox.Dock = DockStyle.Fill;
            _categoryComboBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_categoryComboBox, 0, 3);
            _fields.SetColumnSpan(_categoryComboBox, 2);
            _supplierLabel.AutoSize = true;
            _supplierLabel.Dock = DockStyle.Fill;
            _supplierLabel.Text = "Nhà cung cấp";
            _supplierLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_supplierLabel, 2, 2);
            _fields.SetColumnSpan(_supplierLabel, 2);
            _supplierComboBox.Dock = DockStyle.Fill;
            _supplierComboBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_supplierComboBox, 2, 3);
            _fields.SetColumnSpan(_supplierComboBox, 2);
            _brandLabel.AutoSize = true;
            _brandLabel.Dock = DockStyle.Fill;
            _brandLabel.Text = "Thương hiệu";
            _brandLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_brandLabel, 0, 4);
            _fields.SetColumnSpan(_brandLabel, 2);
            _brandTextBox.Dock = DockStyle.Fill;
            _brandTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_brandTextBox, 0, 5);
            _fields.SetColumnSpan(_brandTextBox, 2);
            _unitLabel.AutoSize = true;
            _unitLabel.Dock = DockStyle.Fill;
            _unitLabel.Text = "Đơn vị tính";
            _unitLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_unitLabel, 2, 4);
            _fields.SetColumnSpan(_unitLabel, 2);
            _unitTextBox.Dock = DockStyle.Fill;
            _unitTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_unitTextBox, 2, 5);
            _fields.SetColumnSpan(_unitTextBox, 2);
            _weightLabel.AutoSize = true;
            _weightLabel.Dock = DockStyle.Fill;
            _weightLabel.Text = "Khối lượng / dung tích";
            _weightLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_weightLabel, 0, 6);
            _fields.SetColumnSpan(_weightLabel, 2);
            _weightTextBox.Dock = DockStyle.Fill;
            _weightTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_weightTextBox, 0, 7);
            _fields.SetColumnSpan(_weightTextBox, 2);
            _statusLabel.AutoSize = true;
            _statusLabel.Dock = DockStyle.Fill;
            _statusLabel.Text = "Trạng thái";
            _statusLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_statusLabel, 2, 6);
            _fields.SetColumnSpan(_statusLabel, 2);
            _statusComboBox.Dock = DockStyle.Fill;
            _statusComboBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_statusComboBox, 2, 7);
            _fields.SetColumnSpan(_statusComboBox, 2);
            _descriptionLabel.AutoSize = true;
            _descriptionLabel.Dock = DockStyle.Fill;
            _descriptionLabel.Text = "Mô tả sản phẩm";
            _descriptionLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_descriptionLabel, 0, 8);
            _fields.SetColumnSpan(_descriptionLabel, 4);
            _descriptionTextBox.Dock = DockStyle.Fill;
            _descriptionTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_descriptionTextBox, 0, 9);
            _fields.SetColumnSpan(_descriptionTextBox, 4);
            _importPriceLabel.AutoSize = true;
            _importPriceLabel.Dock = DockStyle.Fill;
            _importPriceLabel.Text = "Giá nhập (VNĐ)";
            _importPriceLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_importPriceLabel, 0, 10);
            _fields.SetColumnSpan(_importPriceLabel, 2);
            _importPriceTextBox.Dock = DockStyle.Fill;
            _importPriceTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_importPriceTextBox, 0, 11);
            _fields.SetColumnSpan(_importPriceTextBox, 2);
            _sellPriceLabel.AutoSize = true;
            _sellPriceLabel.Dock = DockStyle.Fill;
            _sellPriceLabel.Text = "Giá bán (VNĐ)";
            _sellPriceLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_sellPriceLabel, 2, 10);
            _fields.SetColumnSpan(_sellPriceLabel, 2);
            _sellPriceTextBox.Dock = DockStyle.Fill;
            _sellPriceTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_sellPriceTextBox, 2, 11);
            _fields.SetColumnSpan(_sellPriceTextBox, 2);
            _stockLabel.AutoSize = true;
            _stockLabel.Dock = DockStyle.Fill;
            _stockLabel.Text = "Tồn kho";
            _stockLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_stockLabel, 0, 12);
            _fields.SetColumnSpan(_stockLabel, 2);
            _stockTextBox.Dock = DockStyle.Fill;
            _stockTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_stockTextBox, 0, 13);
            _fields.SetColumnSpan(_stockTextBox, 2);
            _minStockLabel.AutoSize = true;
            _minStockLabel.Dock = DockStyle.Fill;
            _minStockLabel.Text = "Tồn kho tối thiểu";
            _minStockLabel.TextAlign = ContentAlignment.MiddleLeft;
            _fields.Controls.Add(_minStockLabel, 2, 12);
            _fields.SetColumnSpan(_minStockLabel, 2);
            _minStockTextBox.Dock = DockStyle.Fill;
            _minStockTextBox.Margin = new Padding(0, 0, 10, 8);
            _fields.Controls.Add(_minStockTextBox, 2, 13);
            _fields.SetColumnSpan(_minStockTextBox, 2);
            _categoryComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _categoryComboBox.Name = "_categoryComboBox";
            _supplierComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _supplierComboBox.Name = "_supplierComboBox";
            _statusComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _statusComboBox.Name = "_statusComboBox";
            _statusComboBox.Items.AddRange(new object[] { "Đang bán", "Ngừng bán" });
            _statusComboBox.SelectedIndex = 0;
            _descriptionTextBox.Multiline = true;
            _descriptionTextBox.ScrollBars = ScrollBars.Vertical;
            _descriptionTextBox.Dock = DockStyle.Fill;
            _descriptionTextBox.Name = "_descriptionTextBox";
            _importPriceTextBox.Name = "_importPriceTextBox";
            _sellPriceTextBox.Name = "_sellPriceTextBox";
            _stockTextBox.Name = "_stockTextBox";
            _minStockTextBox.Name = "_minStockTextBox";

            _imageGroup.Controls.Add(_clearImageButton);
            _imageGroup.Controls.Add(_uploadImageButton);
            _imageGroup.Controls.Add(_preview);
            _imageGroup.Dock = DockStyle.Fill;
            _imageGroup.Margin = new Padding(10, 6, 0, 6);
            _imageGroup.Padding = new Padding(12);
            _imageGroup.Text = "Ảnh sản phẩm";
            _preview.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            _preview.BorderStyle = BorderStyle.FixedSingle;
            _preview.Location = new Point(16, 40);
            _preview.Name = "_preview";
            _preview.Size = new Size(222, 300);
            _preview.SizeMode = PictureBoxSizeMode.Zoom;
            _uploadImageButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            _uploadImageButton.Location = new Point(16, 350);
            _uploadImageButton.Name = "_uploadImageButton";
            _uploadImageButton.Size = new Size(222, 36);
            _uploadImageButton.Text = "Chọn ảnh...";
            _clearImageButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            _clearImageButton.Location = new Point(16, 394);
            _clearImageButton.Name = "_clearImageButton";
            _clearImageButton.Size = new Size(222, 34);
            _clearImageButton.Text = "Xóa ảnh";

            _detailSummaryLabel.BackColor = Color.FromArgb(241, 245, 249);
            _detailSummaryLabel.Dock = DockStyle.Fill;
            _detailSummaryLabel.Padding = new Padding(10);
            _detailSummaryLabel.Text = "Thông tin tồn kho và trạng thái";
            _detailSummaryLabel.TextAlign = ContentAlignment.MiddleLeft;
            _footer.Controls.Add(_closeButton);
            _footer.Controls.Add(_saveButton);
            _footer.Dock = DockStyle.Fill;
            _footer.FlowDirection = FlowDirection.RightToLeft;
            _footer.Padding = new Padding(0, 8, 0, 0);
            _closeButton.DialogResult = DialogResult.Cancel;
            _closeButton.Margin = new Padding(8, 0, 0, 0);
            _closeButton.Size = new Size(100, 34);
            _closeButton.Text = "Hủy";
            _saveButton.BackColor = Color.FromArgb(37, 99, 235);
            _saveButton.FlatAppearance.BorderSize = 0;
            _saveButton.FlatStyle = FlatStyle.Flat;
            _saveButton.ForeColor = Color.White;
            _saveButton.Margin = new Padding(8, 0, 0, 0);
            _saveButton.Size = new Size(140, 34);
            _saveButton.Text = "Lưu thay đổi";
            AcceptButton = _saveButton;
            CancelButton = _closeButton;

            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1020, 760);
            Controls.Add(_root);
            MinimumSize = new Size(880, 660);
            Name = "frmProductEditor";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Sản phẩm";
            _root.ResumeLayout(false);
            _codePanel.ResumeLayout(false);
            _codePanel.PerformLayout();
            _body.ResumeLayout(false);
            _detailsGroup.ResumeLayout(false);
            _fields.ResumeLayout(false);
            _fields.PerformLayout();
            _imageGroup.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)_preview).EndInit();
            _footer.ResumeLayout(false);
            ResumeLayout(false);
        }

    }
}
