using System.Drawing;
using System.Windows.Forms;

namespace SIMS_WinFormsApp.Views.Catalog
{
    partial class ucCategoryManagement
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel _root;
        private Panel _header;
        private Label _titleLabel;
        private Label _subtitleLabel;
        private FlowLayoutPanel _toolbar;
        private TextBox _searchTextBox;
        private ComboBox _statusComboBox;
        private Button _addButton;
        private Button _importButton;
        private Button _exportCsvButton;
        private Button _exportExcelButton;
        private DataGridView _categoriesGrid;
        private DataGridViewTextBoxColumn _nameColumn;
        private DataGridViewTextBoxColumn _productCountColumn;
        private DataGridViewTextBoxColumn _stateColumn;
        private DataGridViewImageColumn _actionsColumn;
        private TableLayoutPanel _paging;
        private FlowLayoutPanel _pagingInfo;
        private FlowLayoutPanel _pagingNavigation;
        private Label _resultsLabel;
        private Button _previousButton;
        private Label _pageLabel;
        private Button _nextButton;
        private ComboBox _pageSizeComboBox;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            _root = new TableLayoutPanel();
            _header = new Panel();
            _titleLabel = new Label();
            _subtitleLabel = new Label();
            _toolbar = new FlowLayoutPanel();
            _searchTextBox = new TextBox();
            _statusComboBox = new ComboBox();
            _addButton = new Button();
            _importButton = new Button();
            _exportCsvButton = new Button();
            _exportExcelButton = new Button();
            _categoriesGrid = new DataGridView();
            _nameColumn = new DataGridViewTextBoxColumn();
            _productCountColumn = new DataGridViewTextBoxColumn();
            _stateColumn = new DataGridViewTextBoxColumn();
            _actionsColumn = new DataGridViewImageColumn();
            _paging = new TableLayoutPanel();
            _pagingInfo = new FlowLayoutPanel();
            _pagingNavigation = new FlowLayoutPanel();
            _resultsLabel = new Label();
            _previousButton = new Button();
            _pageLabel = new Label();
            _nextButton = new Button();
            _pageSizeComboBox = new ComboBox();
            _root.SuspendLayout();
            _header.SuspendLayout();
            _toolbar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_categoriesGrid).BeginInit();
            _paging.SuspendLayout();
            _pagingInfo.SuspendLayout();
            _pagingNavigation.SuspendLayout();
            SuspendLayout();

            _root.ColumnCount = 1;
            _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _root.Dock = DockStyle.Fill;
            _root.Padding = new Padding(24);
            _root.RowCount = 4;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 82F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
            _root.Controls.Add(_header, 0, 0);
            _root.Controls.Add(_toolbar, 0, 1);
            _root.Controls.Add(_categoriesGrid, 0, 2);
            _root.Controls.Add(_paging, 0, 3);

            _header.Controls.Add(_subtitleLabel);
            _header.Controls.Add(_titleLabel);
            _header.Dock = DockStyle.Fill;
            _titleLabel.AutoSize = true;
            _titleLabel.Font = new Font("Segoe UI", 21F, FontStyle.Bold);
            _titleLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _titleLabel.Location = new Point(0, 0);
            _titleLabel.Text = "Quản lý danh mục";
            _subtitleLabel.AutoSize = true;
            _subtitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _subtitleLabel.Location = new Point(2, 44);
            _subtitleLabel.Text = "Nhóm sản phẩm dùng khi bán hàng và nhập kho";
            _toolbar.Controls.AddRange(new Control[] {
                _searchTextBox, _statusComboBox, _addButton, _importButton, _exportCsvButton, _exportExcelButton
            });
            _toolbar.Dock = DockStyle.Fill;
            _toolbar.WrapContents = false;
            _searchTextBox.Margin = new Padding(0, 7, 8, 0);
            _searchTextBox.Name = "_searchTextBox";
            _searchTextBox.Size = new Size(270, 28);
            _searchTextBox.AccessibleName = "Tìm theo tên danh mục";
            _statusComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _statusComboBox.Items.AddRange(new object[] { "Tất cả trạng thái", "Đang hoạt động", "Vô hiệu hóa" });
            _statusComboBox.Margin = new Padding(4, 7, 8, 0);
            _statusComboBox.Name = "_statusComboBox";
            _statusComboBox.SelectedIndex = 0;
            _statusComboBox.Size = new Size(165, 28);
            _addButton.BackColor = Color.FromArgb(37, 99, 235);
            _addButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _addButton.FlatAppearance.BorderSize = 0;
            _addButton.FlatStyle = FlatStyle.Flat;
            _addButton.ForeColor = Color.White;
            _addButton.Margin = new Padding(4, 5, 4, 0);
            _addButton.Size = new Size(132, 34);
            _addButton.Text = "Thêm danh mục";
            _importButton.BackColor = Color.White;
            _importButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _importButton.FlatAppearance.BorderSize = 1;
            _importButton.FlatStyle = FlatStyle.Flat;
            _importButton.ForeColor = Color.FromArgb(51, 65, 85);
            _importButton.Margin = new Padding(4, 5, 4, 0);
            _importButton.Size = new Size(112, 34);
            _importButton.Text = "Nhập dữ liệu";
            _exportCsvButton.BackColor = Color.White;
            _exportCsvButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _exportCsvButton.FlatAppearance.BorderSize = 1;
            _exportCsvButton.FlatStyle = FlatStyle.Flat;
            _exportCsvButton.ForeColor = Color.FromArgb(51, 65, 85);
            _exportCsvButton.Margin = new Padding(4, 5, 4, 0);
            _exportCsvButton.Size = new Size(94, 34);
            _exportCsvButton.Text = "Xuất CSV";
            _exportExcelButton.BackColor = Color.White;
            _exportExcelButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _exportExcelButton.FlatAppearance.BorderSize = 1;
            _exportExcelButton.FlatStyle = FlatStyle.Flat;
            _exportExcelButton.ForeColor = Color.FromArgb(51, 65, 85);
            _exportExcelButton.Margin = new Padding(4, 5, 4, 0);
            _exportExcelButton.Size = new Size(104, 34);
            _exportExcelButton.Text = "Xuất Excel";

            _categoriesGrid.AllowUserToAddRows = false;
            _categoriesGrid.AllowUserToDeleteRows = false;
            _categoriesGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            _categoriesGrid.BackgroundColor = Color.White;
            _categoriesGrid.BorderStyle = BorderStyle.FixedSingle;
            _categoriesGrid.ColumnHeadersHeight = 42;
            _categoriesGrid.Columns.AddRange(new DataGridViewColumn[] {
                _nameColumn, _productCountColumn, _stateColumn, _actionsColumn
            });
            _categoriesGrid.Dock = DockStyle.Fill;
            _categoriesGrid.MultiSelect = false;
            _categoriesGrid.ReadOnly = true;
            _categoriesGrid.RowHeadersVisible = false;
            _categoriesGrid.RowTemplate.Height = 52;
            _categoriesGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _categoriesGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
            _categoriesGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(51, 65, 85);
            _categoriesGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _categoriesGrid.EnableHeadersVisualStyles = false;
            _categoriesGrid.DefaultCellStyle.Font = new Font("Segoe UI", 9F);
            _categoriesGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
            _categoriesGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
            _categoriesGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
            _nameColumn.FillWeight = 44F;
            _nameColumn.HeaderText = "Tên danh mục";
            _nameColumn.Name = "Name";
            _productCountColumn.FillWeight = 18F;
            _productCountColumn.HeaderText = "Số sản phẩm";
            _productCountColumn.Name = "ProductCount";
            _stateColumn.FillWeight = 20F;
            _stateColumn.HeaderText = "Trạng thái";
            _stateColumn.Name = "Status";
            _actionsColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            _actionsColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
            _actionsColumn.HeaderText = "Thao tác";
            _actionsColumn.ImageLayout = DataGridViewImageCellLayout.Normal;
            _actionsColumn.Name = "Actions";
            _actionsColumn.ToolTipText = "Xem, sửa hoặc đổi trạng thái danh mục";
            _actionsColumn.Width = 120;

            _paging.ColumnCount = 2;
            _paging.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
            _paging.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
            _paging.Dock = DockStyle.Fill;
            _paging.Margin = new Padding(0);
            _paging.RowCount = 1;
            _paging.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _paging.BackColor = Color.White;
            _paging.Controls.Add(_pagingInfo, 0, 0);
            _paging.Controls.Add(_pagingNavigation, 1, 0);
            _pagingInfo.Dock = DockStyle.Fill;
            _pagingInfo.FlowDirection = FlowDirection.LeftToRight;
            _pagingInfo.WrapContents = false;
            _pagingInfo.Padding = new Padding(12, 0, 0, 0);
            _pagingInfo.Controls.Add(_resultsLabel);
            _pagingInfo.Controls.Add(_pageSizeComboBox);
            _resultsLabel.AutoSize = false;
            _resultsLabel.Size = new Size(190, 44);
            _resultsLabel.Margin = new Padding(0, 0, 10, 0);
            _resultsLabel.Text = "Hiển thị 0 danh mục";
            _resultsLabel.TextAlign = ContentAlignment.MiddleLeft;
            _resultsLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _resultsLabel.Font = new Font("Segoe UI", 9F);
            _pagingNavigation.Dock = DockStyle.Fill;
            _pagingNavigation.FlowDirection = FlowDirection.RightToLeft;
            _pagingNavigation.WrapContents = false;
            _pagingNavigation.Padding = new Padding(0, 5, 0, 5);
            _pagingNavigation.Controls.AddRange(new Control[] { _nextButton, _pageLabel, _previousButton });
            _previousButton.FlatStyle = FlatStyle.Flat;
            _previousButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _previousButton.FlatAppearance.BorderSize = 1;
            _previousButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(239, 246, 255);
            _previousButton.BackColor = Color.White;
            _previousButton.ForeColor = Color.FromArgb(51, 65, 85);
            _previousButton.Font = new Font("Segoe UI Symbol", 16F);
            _previousButton.Margin = new Padding(2, 0, 2, 0);
            _previousButton.Size = new Size(36, 34);
            _previousButton.Text = "‹";
            _previousButton.AccessibleName = "Trang trước";
            _nextButton.FlatStyle = FlatStyle.Flat;
            _nextButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _nextButton.FlatAppearance.BorderSize = 1;
            _nextButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(239, 246, 255);
            _nextButton.BackColor = Color.White;
            _nextButton.ForeColor = Color.FromArgb(51, 65, 85);
            _nextButton.Font = new Font("Segoe UI Symbol", 16F);
            _nextButton.Margin = new Padding(2, 0, 2, 0);
            _nextButton.Size = new Size(36, 34);
            _nextButton.Text = "›";
            _nextButton.AccessibleName = "Trang sau";
            _pageLabel.AutoSize = false;
            _pageLabel.Margin = new Padding(8, 0, 8, 0);
            _pageLabel.Size = new Size(112, 34);
            _pageLabel.Text = "Trang 1 / 1";
            _pageLabel.TextAlign = ContentAlignment.MiddleCenter;
            _pageLabel.ForeColor = Color.FromArgb(51, 65, 85);
            _pageLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _pageLabel.BackColor = Color.FromArgb(248, 250, 252);
            _pageSizeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _pageSizeComboBox.Items.AddRange(new object[] { "10 dòng", "20 dòng", "50 dòng" });
            _pageSizeComboBox.Margin = new Padding(0, 8, 0, 0);
            _pageSizeComboBox.SelectedIndex = 0;
            _pageSizeComboBox.Size = new Size(94, 28);

            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(244, 247, 250);
            Controls.Add(_root);
            Name = "ucCategoryManagement";
            Size = new Size(1100, 720);
            _root.ResumeLayout(false);
            _header.ResumeLayout(false);
            _header.PerformLayout();
            _toolbar.ResumeLayout(false);
            _toolbar.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)_categoriesGrid).EndInit();
            _pagingNavigation.ResumeLayout(false);
            _pagingInfo.ResumeLayout(false);
            _paging.ResumeLayout(false);
            ResumeLayout(false);
        }

    }
}
