using System.Drawing;
using System.Windows.Forms;

namespace SIMS_WinFormsApp.Views.Catalog
{
    partial class ucSupplierManagement
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel _root;
        private Panel _header;
        private Label _titleLabel;
        private Label _subtitleLabel;
        private FlowLayoutPanel _toolbar;
        private TextBox _searchTextBox;
        private ComboBox _debtComboBox;
        private Button _addButton;
        private Button _importButton;
        private Button _exportCsvButton;
        private Button _exportExcelButton;
        private DataGridView _suppliersGrid;
        private DataGridViewTextBoxColumn _nameColumn;
        private DataGridViewTextBoxColumn _phoneColumn;
        private DataGridViewTextBoxColumn _emailColumn;
        private DataGridViewTextBoxColumn _addressColumn;
        private DataGridViewTextBoxColumn _itemsColumn;
        private DataGridViewTextBoxColumn _debtColumn;
        private DataGridViewImageColumn _actionsColumn;
        private TableLayoutPanel _paging;
        private FlowLayoutPanel _pagingInfo;
        private FlowLayoutPanel _pagingNavigation;
        private Label _resultsLabel;
        private Button _previousButton;
        private Label _pageLabel;
        private Button _nextButton;
        private ComboBox _pageSizeComboBox;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            _root = new TableLayoutPanel();
            _header = new Panel();
            _titleLabel = new Label();
            _subtitleLabel = new Label();
            _toolbar = new FlowLayoutPanel();
            _searchTextBox = new TextBox();
            _debtComboBox = new ComboBox();
            _addButton = new Button();
            _importButton = new Button();
            _exportCsvButton = new Button();
            _exportExcelButton = new Button();
            _suppliersGrid = new DataGridView();
            _nameColumn = new DataGridViewTextBoxColumn();
            _phoneColumn = new DataGridViewTextBoxColumn();
            _emailColumn = new DataGridViewTextBoxColumn();
            _addressColumn = new DataGridViewTextBoxColumn();
            _itemsColumn = new DataGridViewTextBoxColumn();
            _debtColumn = new DataGridViewTextBoxColumn();
            _actionsColumn = new DataGridViewImageColumn();
            _paging = new TableLayoutPanel();
            _pagingInfo = new FlowLayoutPanel();
            _pagingNavigation = new FlowLayoutPanel();
            _resultsLabel = new Label();
            _previousButton = new Button();
            _pageLabel = new Label();
            _nextButton = new Button();
            _pageSizeComboBox = new ComboBox();
            _root.SuspendLayout();
            _header.SuspendLayout();
            _toolbar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_suppliersGrid).BeginInit();
            _paging.SuspendLayout();
            _pagingInfo.SuspendLayout();
            _pagingNavigation.SuspendLayout();
            SuspendLayout();

            _root.ColumnCount = 1;
            _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _root.Dock = DockStyle.Fill;
            _root.Padding = new Padding(24);
            _root.RowCount = 4;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 82F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
            _root.Controls.Add(_header, 0, 0);
            _root.Controls.Add(_toolbar, 0, 1);
            _root.Controls.Add(_suppliersGrid, 0, 2);
            _root.Controls.Add(_paging, 0, 3);

            _header.Controls.Add(_subtitleLabel);
            _header.Controls.Add(_titleLabel);
            _header.Dock = DockStyle.Fill;
            _titleLabel.AutoSize = true;
            _titleLabel.Font = new Font("Segoe UI", 21F, FontStyle.Bold);
            _titleLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _titleLabel.Location = new Point(0, 0);
            _titleLabel.Text = "Quản lý nhà cung cấp";
            _subtitleLabel.AutoSize = true;
            _subtitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _subtitleLabel.Location = new Point(2, 44);
            _subtitleLabel.Text = "Đối tác nhập hàng, thông tin liên hệ và công nợ";
            _toolbar.Controls.AddRange(new Control[] {
                _searchTextBox, _debtComboBox, _addButton, _importButton, _exportCsvButton, _exportExcelButton
            });
            _toolbar.Dock = DockStyle.Fill;
            _toolbar.WrapContents = false;
            _searchTextBox.Margin = new Padding(0, 7, 8, 0);
            _searchTextBox.Name = "_searchTextBox";
            _searchTextBox.Size = new Size(270, 28);
            _searchTextBox.AccessibleName = "Tìm theo tên, số điện thoại hoặc email";
            _debtComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _debtComboBox.Items.AddRange(new object[] { "Tất cả nhà cung cấp", "Còn công nợ" });
            _debtComboBox.Margin = new Padding(4, 7, 8, 0);
            _debtComboBox.Name = "_debtComboBox";
            _debtComboBox.SelectedIndex = 0;
            _debtComboBox.Size = new Size(165, 28);
            _addButton.FlatStyle = FlatStyle.Flat;
            _addButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _addButton.BackColor = Color.FromArgb(37, 99, 235);
            _addButton.ForeColor = Color.White;
            _addButton.Margin = new Padding(4, 4, 4, 0);
            _addButton.Size = new Size(150, 34);
            _addButton.Text = "Thêm nhà cung cấp";
            _importButton.FlatStyle = FlatStyle.Flat;
            _importButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _importButton.BackColor = Color.White;
            _importButton.ForeColor = Color.FromArgb(51, 65, 85);
            _importButton.Margin = new Padding(4, 4, 4, 0);
            _importButton.Size = new Size(112, 34);
            _importButton.Text = "Nhập dữ liệu";
            _exportCsvButton.FlatStyle = FlatStyle.Flat;
            _exportCsvButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _exportCsvButton.BackColor = Color.White;
            _exportCsvButton.ForeColor = Color.FromArgb(51, 65, 85);
            _exportCsvButton.Margin = new Padding(4, 4, 4, 0);
            _exportCsvButton.Size = new Size(94, 34);
            _exportCsvButton.Text = "Xuất CSV";
            _exportExcelButton.FlatStyle = FlatStyle.Flat;
            _exportExcelButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _exportExcelButton.BackColor = Color.White;
            _exportExcelButton.ForeColor = Color.FromArgb(51, 65, 85);
            _exportExcelButton.Margin = new Padding(4, 4, 4, 0);
            _exportExcelButton.Size = new Size(104, 34);
            _exportExcelButton.Text = "Xuất Excel";

            _suppliersGrid.AllowUserToAddRows = false;
            _suppliersGrid.AllowUserToDeleteRows = false;
            _suppliersGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            _suppliersGrid.BackgroundColor = Color.White;
            _suppliersGrid.BorderStyle = BorderStyle.FixedSingle;
            _suppliersGrid.ColumnHeadersHeight = 42;
            _suppliersGrid.Columns.AddRange(new DataGridViewColumn[] {
                _nameColumn, _phoneColumn, _emailColumn, _addressColumn, _itemsColumn, _debtColumn,
                _actionsColumn
            });
            _suppliersGrid.Dock = DockStyle.Fill;
            _suppliersGrid.MultiSelect = false;
            _suppliersGrid.ReadOnly = true;
            _suppliersGrid.RowHeadersVisible = false;
            _suppliersGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _suppliersGrid.RowTemplate.Height = 52;
            _suppliersGrid.ColumnHeadersHeight = 42;
            _suppliersGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
            _suppliersGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(51, 65, 85);
            _suppliersGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _suppliersGrid.EnableHeadersVisualStyles = false;
            _suppliersGrid.DefaultCellStyle.Font = new Font("Segoe UI", 9F);
            _suppliersGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
            _suppliersGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
            _suppliersGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
            _nameColumn.FillWeight = 16F;
            _nameColumn.HeaderText = "Tên nhà cung cấp";
            _nameColumn.Name = "Name";
            _phoneColumn.FillWeight = 10F;
            _phoneColumn.HeaderText = "Điện thoại";
            _phoneColumn.Name = "Phone";
            _emailColumn.FillWeight = 14F;
            _emailColumn.HeaderText = "Email";
            _emailColumn.Name = "Email";
            _addressColumn.FillWeight = 16F;
            _addressColumn.HeaderText = "Địa chỉ";
            _addressColumn.Name = "Address";
            _itemsColumn.FillWeight = 15F;
            _itemsColumn.HeaderText = "Mặt hàng cung cấp";
            _itemsColumn.Name = "Items";
            _debtColumn.FillWeight = 10F;
            _debtColumn.HeaderText = "Công nợ";
            _debtColumn.Name = "Debt";
            _actionsColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            _actionsColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
            _actionsColumn.HeaderText = "Thao tác";
            _actionsColumn.ImageLayout = DataGridViewImageCellLayout.Normal;
            _actionsColumn.Name = "Actions";
            _actionsColumn.ToolTipText = "Xem, sửa hoặc xóa nhà cung cấp";
            _actionsColumn.Width = 120;

            _paging.ColumnCount = 2;
            _paging.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
            _paging.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
            _paging.Dock = DockStyle.Fill;
            _paging.Margin = new Padding(0);
            _paging.RowCount = 1;
            _paging.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _paging.BackColor = Color.White;
            _paging.Controls.Add(_pagingInfo, 0, 0);
            _paging.Controls.Add(_pagingNavigation, 1, 0);
            _pagingInfo.Dock = DockStyle.Fill;
            _pagingInfo.FlowDirection = FlowDirection.LeftToRight;
            _pagingInfo.WrapContents = false;
            _pagingInfo.Padding = new Padding(12, 0, 0, 0);
            _pagingInfo.Controls.Add(_resultsLabel);
            _pagingInfo.Controls.Add(_pageSizeComboBox);
            _resultsLabel.AutoSize = false;
            _resultsLabel.Size = new Size(190, 44);
            _resultsLabel.Margin = new Padding(0, 0, 10, 0);
            _resultsLabel.Text = "Hiển thị 0 nhà cung cấp";
            _resultsLabel.TextAlign = ContentAlignment.MiddleLeft;
            _resultsLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _resultsLabel.Font = new Font("Segoe UI", 9F);
            _pagingNavigation.Dock = DockStyle.Fill;
            _pagingNavigation.FlowDirection = FlowDirection.RightToLeft;
            _pagingNavigation.WrapContents = false;
            _pagingNavigation.Padding = new Padding(0, 5, 0, 5);
            _pagingNavigation.Controls.AddRange(new Control[] { _nextButton, _pageLabel, _previousButton });
            _previousButton.FlatStyle = FlatStyle.Flat;
            _previousButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _previousButton.FlatAppearance.BorderSize = 1;
            _previousButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(239, 246, 255);
            _previousButton.BackColor = Color.White;
            _previousButton.ForeColor = Color.FromArgb(51, 65, 85);
            _previousButton.Font = new Font("Segoe UI Symbol", 16F);
            _previousButton.Margin = new Padding(2, 0, 2, 0);
            _previousButton.Size = new Size(36, 34);
            _previousButton.Text = "‹";
            _previousButton.AccessibleName = "Trang trước";
            _nextButton.FlatStyle = FlatStyle.Flat;
            _nextButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _nextButton.FlatAppearance.BorderSize = 1;
            _nextButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(239, 246, 255);
            _nextButton.BackColor = Color.White;
            _nextButton.ForeColor = Color.FromArgb(51, 65, 85);
            _nextButton.Font = new Font("Segoe UI Symbol", 16F);
            _nextButton.Margin = new Padding(2, 0, 2, 0);
            _nextButton.Size = new Size(36, 34);
            _nextButton.Text = "›";
            _nextButton.AccessibleName = "Trang sau";
            _pageLabel.AutoSize = false;
            _pageLabel.Margin = new Padding(8, 0, 8, 0);
            _pageLabel.Size = new Size(112, 34);
            _pageLabel.Text = "Trang 1 / 1";
            _pageLabel.TextAlign = ContentAlignment.MiddleCenter;
            _pageLabel.ForeColor = Color.FromArgb(51, 65, 85);
            _pageLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _pageLabel.BackColor = Color.FromArgb(248, 250, 252);
            _pageSizeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _pageSizeComboBox.Items.AddRange(new object[] { "10 dòng", "20 dòng", "50 dòng" });
            _pageSizeComboBox.Margin = new Padding(0, 8, 0, 0);
            _pageSizeComboBox.SelectedIndex = 0;
            _pageSizeComboBox.Size = new Size(94, 28);

            Controls.Add(_root);
            Name = "ucSupplierManagement";
            Size = new Size(1100, 680);
            _pagingNavigation.ResumeLayout(false);
            _pagingInfo.ResumeLayout(false);
            _paging.ResumeLayout(false);
            _toolbar.ResumeLayout(false);
            _toolbar.PerformLayout();
            _header.ResumeLayout(false);
            _header.PerformLayout();
            _root.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)_suppliersGrid).EndInit();
            ResumeLayout(false);
        }

    }
}
