using System.Drawing;
using System.Windows.Forms;

namespace SIMS_WinFormsApp.UI.Controls.Pos
{
    partial class PosPageControl
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel _root;
        private Panel _header;
        private Label _pageTitle;
        private Label _cashierNameLabel;
        private SplitContainer _body;
        private Panel _catalogCard;
        private TableLayoutPanel _catalogLayout;
        private Label _catalogTitle;
        private TableLayoutPanel _searchLayout;
        private TextBox _productSearch;
        private ComboBox _productCategory;
        private Button _scanBarcodeButton;
        private FlowLayoutPanel _productCardsPanel;
        private Panel _saleCard;
        private TableLayoutPanel _saleLayout;
        private SplitContainer _cartCheckoutSplit;
        private TableLayoutPanel _cartAreaLayout;
        private Panel _checkoutScrollPanel;
        private TableLayoutPanel _checkoutLayout;
        private Label _customerLabel;
        private TableLayoutPanel _customerLayout;
        private TextBox _customerTextBox;
        private Button _customerSearchButton;
        private Button _pickCustomerButton;
        private Button _clearCustomerButton;
        private CheckBox _usePointsCheckBox;
        private Label _cartLabel;
        private DataGridView _cartGrid;
        private DataGridViewTextBoxColumn _cartProductName;
        private DataGridViewTextBoxColumn _cartUnitPrice;
        private DataGridViewTextBoxColumn _cartQuantity;
        private DataGridViewTextBoxColumn _cartLineTotal;
        private DataGridViewButtonColumn _cartRemove;
        private TableLayoutPanel _promoLayout;
        private Label _promoLabel;
        private TextBox _promoTextBox;
        private Button _applyPromoButton;
        private TableLayoutPanel _totalsLayout;
        private Label _subtotalCaption;
        private Label _subtotalValue;
        private Label _discountCaption;
        private Label _discountValue;
        private Label _vatCaption;
        private Label _vatValue;
        private Label _pointsCaption;
        private Label _pointsValue;
        private Label _grandTotalCaption;
        private Label _grandTotalValue;
        private TableLayoutPanel _paymentLayout;
        private Label _paymentCaption;
        private ComboBox _paymentMethod;
        private TableLayoutPanel _actionsLayout;
        private Button _holdButton;
        private Button _heldCartsButton;
        private Button _checkoutButton;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            _root = new TableLayoutPanel();
            _header = new Panel();
            _pageTitle = new Label();
            _cashierNameLabel = new Label();
            _body = new SplitContainer();
            _catalogCard = new Panel();
            _catalogLayout = new TableLayoutPanel();
            _catalogTitle = new Label();
            _searchLayout = new TableLayoutPanel();
            _productSearch = new TextBox();
            _productCategory = new ComboBox();
            _scanBarcodeButton = new Button();
            _productCardsPanel = new FlowLayoutPanel();
            _saleCard = new Panel();
            _saleLayout = new TableLayoutPanel();
            _cartCheckoutSplit = new SplitContainer();
            _cartAreaLayout = new TableLayoutPanel();
            _checkoutScrollPanel = new Panel();
            _checkoutLayout = new TableLayoutPanel();
            _customerLabel = new Label();
            _customerLayout = new TableLayoutPanel();
            _customerTextBox = new TextBox();
            _customerSearchButton = new Button();
            _pickCustomerButton = new Button();
            _clearCustomerButton = new Button();
            _usePointsCheckBox = new CheckBox();
            _cartLabel = new Label();
            _cartGrid = new DataGridView();
            _cartProductName = new DataGridViewTextBoxColumn();
            _cartUnitPrice = new DataGridViewTextBoxColumn();
            _cartQuantity = new DataGridViewTextBoxColumn();
            _cartLineTotal = new DataGridViewTextBoxColumn();
            _cartRemove = new DataGridViewButtonColumn();
            _promoLayout = new TableLayoutPanel();
            _promoLabel = new Label();
            _promoTextBox = new TextBox();
            _applyPromoButton = new Button();
            _totalsLayout = new TableLayoutPanel();
            _subtotalCaption = new Label();
            _subtotalValue = new Label();
            _discountCaption = new Label();
            _discountValue = new Label();
            _vatCaption = new Label();
            _vatValue = new Label();
            _pointsCaption = new Label();
            _pointsValue = new Label();
            _grandTotalCaption = new Label();
            _grandTotalValue = new Label();
            _paymentLayout = new TableLayoutPanel();
            _paymentCaption = new Label();
            _paymentMethod = new ComboBox();
            _actionsLayout = new TableLayoutPanel();
            _holdButton = new Button();
            _heldCartsButton = new Button();
            _checkoutButton = new Button();
            _root.SuspendLayout();
            _header.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_body).BeginInit();
            _body.Panel1.SuspendLayout();
            _body.Panel2.SuspendLayout();
            _body.SuspendLayout();
            _catalogCard.SuspendLayout();
            _catalogLayout.SuspendLayout();
            _searchLayout.SuspendLayout();
            _saleCard.SuspendLayout();
            _saleLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_cartCheckoutSplit).BeginInit();
            _cartCheckoutSplit.Panel1.SuspendLayout();
            _cartCheckoutSplit.Panel2.SuspendLayout();
            _cartCheckoutSplit.SuspendLayout();
            _cartAreaLayout.SuspendLayout();
            _checkoutScrollPanel.SuspendLayout();
            _checkoutLayout.SuspendLayout();
            _customerLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_cartGrid).BeginInit();
            _promoLayout.SuspendLayout();
            _totalsLayout.SuspendLayout();
            _actionsLayout.SuspendLayout();
            SuspendLayout();

            _root.ColumnCount = 1;
            _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _root.Dock = DockStyle.Fill;
            _root.Padding = new Padding(20);
            _root.RowCount = 2;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 76F));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _root.Controls.Add(_header, 0, 0);
            _root.Controls.Add(_body, 0, 1);

            _header.BackColor = Color.White;
            _header.Controls.Add(_cashierNameLabel);
            _header.Controls.Add(_pageTitle);
            _header.Dock = DockStyle.Fill;
            _pageTitle.AutoSize = true;
            _pageTitle.Font = new Font("Segoe UI", 21F, FontStyle.Bold);
            _pageTitle.ForeColor = Color.FromArgb(15, 23, 42);
            _pageTitle.Location = new Point(8, 4);
            _pageTitle.Text = "Bán hàng tại quầy";
            _cashierNameLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            _cashierNameLabel.AutoSize = true;
            _cashierNameLabel.ForeColor = Color.FromArgb(71, 85, 105);
            _cashierNameLabel.Location = new Point(650, 28);
            _cashierNameLabel.Text = "Nhân viên:";

            _body.BackColor = Color.FromArgb(244, 247, 250);
            _body.BorderStyle = BorderStyle.None;
            _body.Dock = DockStyle.Fill;
            _body.Margin = new Padding(0, 14, 0, 0);
            _body.Name = "_body";
            _body.Orientation = Orientation.Vertical;
            _body.Panel1MinSize = 360;
            _body.Panel2MinSize = 320;
            _body.Size = new Size(1140, 620);
            _body.SplitterDistance = 720;
            _body.SplitterWidth = 8;
            _body.TabStop = false;
            _body.Panel1.Controls.Add(_catalogCard);
            _body.Panel2.Controls.Add(_saleCard);

            _catalogCard.BackColor = Color.White;
            _catalogCard.BorderStyle = BorderStyle.FixedSingle;
            _catalogCard.Controls.Add(_catalogLayout);
            _catalogCard.Dock = DockStyle.Fill;
            _catalogCard.Margin = Padding.Empty;
            _catalogCard.Padding = new Padding(12);
            _catalogLayout.ColumnCount = 1;
            _catalogLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _catalogLayout.Dock = DockStyle.Fill;
            _catalogLayout.RowCount = 3;
            _catalogLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            _catalogLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            _catalogLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _catalogLayout.Controls.Add(_catalogTitle, 0, 0);
            _catalogLayout.Controls.Add(_searchLayout, 0, 1);
            _catalogLayout.Controls.Add(_productCardsPanel, 0, 2);
            _catalogTitle.Dock = DockStyle.Fill;
            _catalogTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            _catalogTitle.Text = "Danh sách sản phẩm";
            _catalogTitle.TextAlign = ContentAlignment.MiddleLeft;
            _searchLayout.ColumnCount = 3;
            _searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
            _searchLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 92F));
            _searchLayout.Dock = DockStyle.Fill;
            _searchLayout.RowCount = 1;
            _searchLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _searchLayout.Controls.Add(_productSearch, 0, 0);
            _searchLayout.Controls.Add(_productCategory, 1, 0);
            _searchLayout.Controls.Add(_scanBarcodeButton, 2, 0);
            _productSearch.Dock = DockStyle.Fill;
            _productSearch.Margin = new Padding(0, 4, 8, 4);
            _productSearch.Name = "_productSearch";
            _productSearch.AccessibleName = "Tìm sản phẩm theo tên hoặc danh mục";
            _productCategory.Dock = DockStyle.Fill;
            _productCategory.DropDownStyle = ComboBoxStyle.DropDownList;
            _productCategory.Items.AddRange(new object[] { "Tất cả danh mục" });
            _productCategory.Margin = new Padding(0, 4, 8, 4);
            _productCategory.Name = "_productCategory";
            _productCategory.SelectedIndex = 0;
            _scanBarcodeButton.Dock = DockStyle.Fill;
            _scanBarcodeButton.FlatStyle = FlatStyle.Flat;
            _scanBarcodeButton.FlatAppearance.BorderColor = Color.FromArgb(37, 99, 235);
            _scanBarcodeButton.ForeColor = Color.FromArgb(37, 99, 235);
            _scanBarcodeButton.Margin = new Padding(0, 4, 0, 4);
            _scanBarcodeButton.Name = "_scanBarcodeButton";
            _scanBarcodeButton.Text = "Quét mã";
            _scanBarcodeButton.UseVisualStyleBackColor = true;

            _productCardsPanel.AutoScroll = true;
            _productCardsPanel.BackColor = Color.FromArgb(248, 250, 252);
            _productCardsPanel.Dock = DockStyle.Fill;
            _productCardsPanel.FlowDirection = FlowDirection.LeftToRight;
            _productCardsPanel.Name = "_productCardsPanel";
            _productCardsPanel.Padding = new Padding(8);
            _productCardsPanel.WrapContents = true;

            _saleCard.BackColor = Color.White;
            _saleCard.BorderStyle = BorderStyle.FixedSingle;
            _saleCard.Controls.Add(_saleLayout);
            _saleCard.Dock = DockStyle.Fill;
            _saleCard.Margin = Padding.Empty;
            _saleCard.Padding = new Padding(12);
            _saleLayout.ColumnCount = 1;
            _saleLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _saleLayout.Dock = DockStyle.Fill;
            _saleLayout.RowCount = 2;
            _saleLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 88F));
            _saleLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _saleLayout.Controls.Add(_customerLayout, 0, 0);
            _saleLayout.Controls.Add(_cartCheckoutSplit, 0, 1);

            _cartCheckoutSplit.BackColor = Color.FromArgb(203, 213, 225);
            _cartCheckoutSplit.BorderStyle = BorderStyle.None;
            _cartCheckoutSplit.Dock = DockStyle.Fill;
            _cartCheckoutSplit.FixedPanel = FixedPanel.None;
            _cartCheckoutSplit.IsSplitterFixed = false;
            _cartCheckoutSplit.Cursor = Cursors.HSplit;
            _cartCheckoutSplit.Name = "_cartCheckoutSplit";
            _cartCheckoutSplit.Orientation = Orientation.Horizontal;
            _cartCheckoutSplit.Panel1MinSize = 90;
            _cartCheckoutSplit.Panel2MinSize = 100;
            _cartCheckoutSplit.Size = new Size(340, 430);
            _cartCheckoutSplit.SplitterDistance = 160;
            _cartCheckoutSplit.SplitterWidth = 10;
            _cartCheckoutSplit.Panel1.Controls.Add(_cartAreaLayout);
            _cartCheckoutSplit.Panel2.Controls.Add(_checkoutScrollPanel);

            _cartAreaLayout.ColumnCount = 1;
            _cartAreaLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _cartAreaLayout.Dock = DockStyle.Fill;
            _cartAreaLayout.RowCount = 2;
            _cartAreaLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _cartAreaLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _cartAreaLayout.Controls.Add(_cartLabel, 0, 0);
            _cartAreaLayout.Controls.Add(_cartGrid, 0, 1);

            _checkoutScrollPanel.AutoScroll = true;
            _checkoutScrollPanel.AutoScrollMinSize = new Size(0, 314);
            _checkoutScrollPanel.BackColor = Color.White;
            _checkoutScrollPanel.Dock = DockStyle.Fill;
            _checkoutScrollPanel.Name = "_checkoutScrollPanel";
            _checkoutScrollPanel.Padding = new Padding(0);
            _checkoutScrollPanel.Controls.Add(_checkoutLayout);

            _checkoutLayout.ColumnCount = 1;
            _checkoutLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _checkoutLayout.Dock = DockStyle.Top;
            _checkoutLayout.Height = 314;
            _checkoutLayout.Margin = Padding.Empty;
            _checkoutLayout.MinimumSize = new Size(0, 314);
            _checkoutLayout.RowCount = 4;
            _checkoutLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            _checkoutLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _checkoutLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
            _checkoutLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 86F));
            _checkoutLayout.Controls.Add(_promoLayout, 0, 0);
            _checkoutLayout.Controls.Add(_totalsLayout, 0, 1);
            _checkoutLayout.Controls.Add(_paymentLayout, 0, 2);
            _checkoutLayout.Controls.Add(_actionsLayout, 0, 3);

            _customerLayout.ColumnCount = 4;
            _customerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _customerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42F));
            _customerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42F));
            _customerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42F));
            _customerLayout.Dock = DockStyle.Fill;
            _customerLayout.RowCount = 3;
            _customerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 22F));
            _customerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            _customerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _customerLayout.Controls.Add(_customerLabel, 0, 0);
            _customerLayout.Controls.Add(_customerTextBox, 0, 1);
            _customerLayout.SetColumnSpan(_customerTextBox, 1);
            _customerLayout.Controls.Add(_customerSearchButton, 1, 1);
            _customerLayout.Controls.Add(_pickCustomerButton, 2, 1);
            _customerLayout.Controls.Add(_clearCustomerButton, 3, 1);
            _customerLayout.Controls.Add(_usePointsCheckBox, 0, 2);
            _customerLayout.SetColumnSpan(_usePointsCheckBox, 4);
            _customerLabel.AutoSize = true;
            _customerLabel.Dock = DockStyle.Fill;
            _customerLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _customerLabel.Text = "Khách hàng";
            _customerTextBox.Dock = DockStyle.Fill;
            _customerTextBox.Margin = new Padding(0, 2, 6, 2);
            _customerTextBox.Name = "_customerTextBox";
            _customerSearchButton.Dock = DockStyle.Fill;
            _customerSearchButton.FlatStyle = FlatStyle.Flat;
            _customerSearchButton.Margin = new Padding(0, 2, 4, 2);
            _customerSearchButton.Text = "Tìm";
            _pickCustomerButton.Dock = DockStyle.Fill;
            _pickCustomerButton.FlatStyle = FlatStyle.Flat;
            _pickCustomerButton.Margin = new Padding(0, 2, 4, 2);
            _pickCustomerButton.Text = "...";
            _pickCustomerButton.AccessibleName = "Chọn khách hàng";
            _clearCustomerButton.Dock = DockStyle.Fill;
            _clearCustomerButton.FlatStyle = FlatStyle.Flat;
            _clearCustomerButton.Margin = new Padding(0, 2, 0, 2);
            _clearCustomerButton.Text = "Xóa";
            _usePointsCheckBox.AutoSize = true;
            _usePointsCheckBox.Dock = DockStyle.Fill;
            _usePointsCheckBox.Text = "Dùng điểm thưởng";
            _usePointsCheckBox.Visible = false;

            _cartLabel.AutoSize = true;
            _cartLabel.Dock = DockStyle.Fill;
            _cartLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _cartLabel.Text = "Giỏ hàng";
            _cartLabel.Padding = new Padding(0, 0, 0, 2);
            _cartGrid.AllowUserToAddRows = false;
            _cartGrid.AllowUserToDeleteRows = false;
            _cartGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            _cartGrid.BackgroundColor = Color.White;
            _cartGrid.BorderStyle = BorderStyle.None;
            _cartGrid.ColumnHeadersHeight = 34;
            _cartGrid.Columns.AddRange(new DataGridViewColumn[] {
                _cartProductName, _cartUnitPrice, _cartQuantity, _cartLineTotal, _cartRemove
            });
            _cartGrid.Dock = DockStyle.Fill;
            _cartGrid.Margin = new Padding(0);
            _cartGrid.MultiSelect = false;
            _cartGrid.RowHeadersVisible = false;
            _cartGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _cartProductName.FillWeight = 30F;
            _cartProductName.HeaderText = "Sản phẩm";
            _cartProductName.Name = "CartProductName";
            _cartProductName.ReadOnly = true;
            _cartUnitPrice.FillWeight = 20F;
            _cartUnitPrice.HeaderText = "Đơn giá";
            _cartUnitPrice.Name = "CartUnitPrice";
            _cartUnitPrice.ReadOnly = true;
            _cartQuantity.FillWeight = 12F;
            _cartQuantity.HeaderText = "SL";
            _cartQuantity.Name = "CartQuantity";
            _cartLineTotal.FillWeight = 22F;
            _cartLineTotal.HeaderText = "Thành tiền";
            _cartLineTotal.Name = "CartLineTotal";
            _cartLineTotal.ReadOnly = true;
            _cartRemove.FillWeight = 16F;
            _cartRemove.HeaderText = "";
            _cartRemove.Name = "CartRemove";
            _cartRemove.Text = "Xóa";
            _cartRemove.UseColumnTextForButtonValue = true;

            _promoLayout.ColumnCount = 3;
            _promoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 64F));
            _promoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _promoLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 88F));
            _promoLayout.Dock = DockStyle.Fill;
            _promoLayout.RowCount = 1;
            _promoLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _promoLayout.Controls.Add(_promoLabel, 0, 0);
            _promoLayout.Controls.Add(_promoTextBox, 1, 0);
            _promoLayout.Controls.Add(_applyPromoButton, 2, 0);
            _promoLabel.Dock = DockStyle.Fill;
            _promoLabel.Text = "Mã KM";
            _promoLabel.TextAlign = ContentAlignment.MiddleLeft;
            _promoTextBox.Dock = DockStyle.Fill;
            _promoTextBox.Margin = new Padding(0, 4, 6, 4);
            _promoTextBox.Name = "_promoTextBox";
            _applyPromoButton.Dock = DockStyle.Fill;
            _applyPromoButton.FlatStyle = FlatStyle.Flat;
            _applyPromoButton.ForeColor = Color.FromArgb(37, 99, 235);
            _applyPromoButton.Margin = new Padding(0, 4, 0, 4);
            _applyPromoButton.Text = "Áp dụng";

            _totalsLayout.ColumnCount = 2;
            _totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55F));
            _totalsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F));
            _totalsLayout.Dock = DockStyle.Fill;
            _totalsLayout.RowCount = 5;
            _totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            _totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            _totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            _totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            _totalsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
            _subtotalCaption.Dock = DockStyle.Fill;
            _subtotalCaption.Text = "Tạm tính";
            _subtotalCaption.TextAlign = ContentAlignment.MiddleLeft;
            _subtotalValue.Dock = DockStyle.Fill;
            _subtotalValue.Text = "0 VNĐ";
            _subtotalValue.TextAlign = ContentAlignment.MiddleRight;
            _totalsLayout.Controls.Add(_subtotalCaption, 0, 0);
            _totalsLayout.Controls.Add(_subtotalValue, 1, 0);
            _discountCaption.Dock = DockStyle.Fill;
            _discountCaption.Text = "Giảm giá";
            _discountCaption.TextAlign = ContentAlignment.MiddleLeft;
            _discountValue.Dock = DockStyle.Fill;
            _discountValue.Text = "0 VNĐ";
            _discountValue.TextAlign = ContentAlignment.MiddleRight;
            _totalsLayout.Controls.Add(_discountCaption, 0, 1);
            _totalsLayout.Controls.Add(_discountValue, 1, 1);
            _vatCaption.Dock = DockStyle.Fill;
            _vatCaption.Text = "VAT";
            _vatCaption.TextAlign = ContentAlignment.MiddleLeft;
            _vatValue.Dock = DockStyle.Fill;
            _vatValue.Text = "0 VNĐ";
            _vatValue.TextAlign = ContentAlignment.MiddleRight;
            _totalsLayout.Controls.Add(_vatCaption, 0, 2);
            _totalsLayout.Controls.Add(_vatValue, 1, 2);
            _pointsCaption.Dock = DockStyle.Fill;
            _pointsCaption.Text = "Trừ điểm";
            _pointsCaption.TextAlign = ContentAlignment.MiddleLeft;
            _pointsValue.Dock = DockStyle.Fill;
            _pointsValue.Text = "0 VNĐ";
            _pointsValue.TextAlign = ContentAlignment.MiddleRight;
            _totalsLayout.Controls.Add(_pointsCaption, 0, 3);
            _totalsLayout.Controls.Add(_pointsValue, 1, 3);
            _grandTotalCaption.Dock = DockStyle.Fill;
            _grandTotalCaption.Text = "Tổng cộng";
            _grandTotalCaption.TextAlign = ContentAlignment.MiddleLeft;
            _grandTotalValue.Dock = DockStyle.Fill;
            _grandTotalValue.Text = "0 VNĐ";
            _grandTotalValue.TextAlign = ContentAlignment.MiddleRight;
            _totalsLayout.Controls.Add(_grandTotalCaption, 0, 4);
            _totalsLayout.Controls.Add(_grandTotalValue, 1, 4);
            _grandTotalCaption.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _grandTotalValue.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            _grandTotalValue.ForeColor = Color.FromArgb(37, 99, 235);

            _paymentCaption.Dock = DockStyle.Fill;
            _paymentCaption.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            _paymentCaption.Text = "Hình thức thanh toán";
            _paymentLayout.ColumnCount = 2;
            _paymentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
            _paymentLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _paymentLayout.Dock = DockStyle.Fill;
            _paymentLayout.RowCount = 1;
            _paymentLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _paymentLayout.Controls.Add(_paymentCaption, 0, 0);
            _paymentMethod.DropDownStyle = ComboBoxStyle.DropDownList;
            _paymentMethod.Dock = DockStyle.Fill;
            _paymentMethod.Margin = new Padding(0, 14, 0, 14);
            _paymentMethod.Name = "_paymentMethod";
            _paymentLayout.Controls.Add(_paymentMethod, 1, 0);

            _actionsLayout.ColumnCount = 2;
            _actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _actionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            _actionsLayout.Dock = DockStyle.Fill;
            _actionsLayout.RowCount = 2;
            _actionsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 46F));
            _actionsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 54F));
            _actionsLayout.Controls.Add(_holdButton, 0, 0);
            _actionsLayout.Controls.Add(_heldCartsButton, 1, 0);
            _actionsLayout.Controls.Add(_checkoutButton, 0, 1);
            _actionsLayout.SetColumnSpan(_checkoutButton, 2);
            _holdButton.Dock = DockStyle.Fill;
            _holdButton.FlatStyle = FlatStyle.Flat;
            _holdButton.Margin = new Padding(0, 2, 4, 4);
            _holdButton.Text = "Tạm giữ";
            _heldCartsButton.Dock = DockStyle.Fill;
            _heldCartsButton.FlatStyle = FlatStyle.Flat;
            _heldCartsButton.Margin = new Padding(4, 2, 0, 4);
            _heldCartsButton.Text = "Giỏ đã giữ";
            _checkoutButton.BackColor = Color.FromArgb(37, 99, 235);
            _checkoutButton.Dock = DockStyle.Fill;
            _checkoutButton.FlatAppearance.BorderSize = 0;
            _checkoutButton.FlatStyle = FlatStyle.Flat;
            _checkoutButton.ForeColor = Color.White;
            _checkoutButton.Margin = new Padding(0, 2, 0, 0);
            _checkoutButton.Text = "Thanh toán";

            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(244, 247, 250);
            Controls.Add(_root);
            Name = "PosPageControl";
            Size = new Size(1180, 760);
            _root.ResumeLayout(false);
            _header.ResumeLayout(false);
            _header.PerformLayout();
            _body.Panel1.ResumeLayout(false);
            _body.Panel2.ResumeLayout(false);
            _body.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)_body).EndInit();
            _catalogCard.ResumeLayout(false);
            _catalogLayout.ResumeLayout(false);
            _searchLayout.ResumeLayout(false);
            _searchLayout.PerformLayout();
            _saleCard.ResumeLayout(false);
            _checkoutLayout.ResumeLayout(false);
            _checkoutScrollPanel.ResumeLayout(false);
            _cartAreaLayout.ResumeLayout(false);
            _cartCheckoutSplit.Panel1.ResumeLayout(false);
            _cartCheckoutSplit.Panel2.ResumeLayout(false);
            _cartCheckoutSplit.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)_cartCheckoutSplit).EndInit();
            _saleLayout.ResumeLayout(false);
            _saleLayout.PerformLayout();
            _customerLayout.ResumeLayout(false);
            _customerLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)_cartGrid).EndInit();
            _promoLayout.ResumeLayout(false);
            _promoLayout.PerformLayout();
            _totalsLayout.ResumeLayout(false);
            _actionsLayout.ResumeLayout(false);
            _paymentLayout.ResumeLayout(false);
            ResumeLayout(false);
        }

    }
}
